feature/ added trivy vulnerability scan

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -20,6 +20,28 @@ on:
       IMAGE_REGISTRY_PASSWORD:
         required: true
         description: Secret for Image Registry
+      DEFECTDOJO_API_TOKEN:
+        required: true
+        description: DEFECTDOJO api token
+      DEFECTDOJO_URL:
+        required: true
+        description: DEFECDOJO url
+      SMTP_HOST: 
+        required: true
+        description: SMTP Server Host
+      SMTP_EMAIL: 
+        required: true
+        description: SMTP Server Email
+      SMTP_USER: 
+        required: true
+        description: SMTP Server User
+      SMTP_PORT:
+        required: true
+        description: SMTP Server Port
+      SMTP_PASSWORD:
+        required: true
+        description: SMTP Server Password
+
     inputs:
       docker_context_path:
         description: Docker context path
@@ -67,6 +89,20 @@ on:
         description: Username of Image Registry for logging
         type: string
         required: true
+      enable_trivy_gate:
+        description: Fail the workflow if critical vulnerabilities are found during Trivy scan
+        required: false
+        type: boolean
+        default: false
+      trivy_scan_timeout:
+        description: Trivy scan timeout
+        required: false
+        type: string
+        default: 15m0s
+      trivy_notification_receivers:
+        description: Trivy scan results notification receivers
+        required: true
+        type: string
 jobs:
   build-docker:
     runs-on: ubuntu-latest
@@ -94,9 +130,6 @@ jobs:
         id: meta
         uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
         with:
-          # image name should ideally be ghcr.io/${{ secrets.REPOSITORY_OWNER }}/${{ inputs.image_name }}
-          # but it throws error while pulling image with this. it is building the image but not able to push in github container registry
-          # so, don't use secrets for this step
           images: |
             ${{ inputs.image_registry }}/${{ inputs.image_name }}
           tags: |
@@ -121,11 +154,84 @@ jobs:
           else
             echo "${{ inputs.dot_env_file_production }}" >> ${{ inputs.docker_context_path }}/.env
           fi
-      - name: Build and push Docker image to github container registry
+      - name: Build Docker image
         uses: docker/build-push-action@v3
         with:
           context: ${{ inputs.docker_context_path }}
           file: ${{ inputs.dockerfile_path }}
-          push: true
+          push: false
+          load: true
           tags: ${{ steps.meta.outputs.tags }}
           labels: ${{ steps.meta.outputs.labels }}
+
+      - name: Get the scan result as Json format
+        uses: aquasecurity/trivy-action@7b7aa264d83dc58691451798b4d117d53d21edfe
+        with:
+          image-ref: ${{ steps.meta.outputs.tags }}
+          format: json
+          output: trivy-report.json
+          severity: CRITICAL,HIGH,MEDIUM
+          timeout: ${{ inputs.trivy_scan_timeout }}
+      - name: Upload scan results to Calance trivy dashboard
+        run: |
+          echo "Uploading Trivy scan results to dashboard..."
+
+          VERSION=${{ steps.version.outputs.build_version }}
+          ENVIRONMENT="${{ steps.cluster_environment.outputs.cluster_environment }}"
+          SCAN_FILE="trivy-report.json"
+
+          HTTP_STATUS=$(curl -s -o response.json -w "%{http_code}" -X POST \
+            -H "Authorization: Token ${{ secrets.DEFECTDOJO_API_TOKEN }}" \
+            -F "file=@$SCAN_FILE" \
+            -F "scan_type=Trivy Scan" \
+            -F "product_name=${{ github.event.repository.name }}" \
+            -F "engagement_name=$VERSION Container Security Scan $ENVIRONMENT" \
+            -F "version=$VERSION" \
+            -F "test_title=Trivy Scan $VERSION" \
+            -F "auto_create_context=true" \
+            -F "tags=$VERSION,ci-cd,container-security" \
+            -F "environment=$ENVIRONMENT" \
+            -F "branch_tag=${{ github.ref_name }}" \
+            -F "commit_hash=${{ github.sha }}" \
+            -F "close_old_findings=true" \
+            "${{ secrets.DEFECTDOJO_URL }}/api/v2/reimport-scan/")
+
+          echo "Status Code: $HTTP_STATUS"
+          cat response.json
+
+          if [ "$HTTP_STATUS" -ge 200 ] && [ "$HTTP_STATUS" -lt 300 ]; then
+            echo "✓ Upload successful"
+          else
+            echo "✗ Upload failed with status $HTTP_STATUS"
+            exit 1
+          fi
+      - name: Extracting Vulnerability index for Notification
+        uses: Calance-US/calance-workflows/actions/vulnerability-notification@3214-trivy-workflow-update-into-build
+        with:
+          smtp-server: ${{secrets.SMTP_HOST}}
+          smtp-port: ${{secrets.SMTP_PORT}}
+          smtp-username: ${{secrets.SMTP_USER}}
+          smtp-password: ${{secrets.SMTP_PASSWORD}}
+          sender-email: ${{secrets.SMTP_EMAIL}}
+          trivy_notification_receivers: ${{inputs.trivy_notification_receivers}}
+          repository: ${{github.event.repository.name}}
+          tag: ${{github.ref_name}}
+      - name: Upload Trivy scan results as an artifact
+        uses: actions/upload-artifact@v4
+        with:
+          name: trivy-report
+          path: ${{ github.workspace }}/trivy-report.json
+      - name: Check Trivy scan results
+        if: ${{ inputs.enable_trivy_gate }}
+        run: |
+          CRITICAL_COUNT=$(jq '[.Results[].Vulnerabilities[] | select(.Severity=="CRITICAL")] | length' trivy-report.json)
+          echo "Found $CRITICAL_COUNT critical vulnerabilities"
+          if [ "$CRITICAL_COUNT" -gt 0 ]; then
+            echo "Too many critical vulnerabilities. Exiting workflow."
+            exit 1
+          fi
+      - name: Push Docker image
+        if: ${{ !inputs.enable_trivy_gate || success() }}
+        run: |
+          echo "Pushing Docker image to registry..."
+          docker push ${{ steps.meta.outputs.tags }}
