Added the validation condition of keep_at_least in both envs.

diff --git a/.github/workflows/clean-image-registry.yml b/.github/workflows/clean-image-registry.yml
--- a/.github/workflows/clean-image-registry.yml
+++ b/.github/workflows/clean-image-registry.yml
@@ -37,6 +37,12 @@ jobs:
     name: Delete old unused container images
     runs-on: ubuntu-latest
     steps:
+      - name: Validating inputs for production
+        run: | 
+          [[ if ${{ github.event.inputs.prod_keep_at_least }} < 10 ]]; then
+                echo "Provided value of prod_keep_at_least cannot be less than 10";
+                exit 1;
+          fi
       - name: Delete old containers in Production
         id: delete-packages-prod
         uses: snok/container-retention-policy@v2
@@ -51,8 +57,15 @@ jobs:
   
   clean-ghcr-testing:
     name: Delete old unused container images
+    if: github.event.inputs.testing_keep_at_least > 5
     runs-on: ubuntu-latest
     steps:
+      - name: Validating inputs for testing
+        run: |
+          [[ if ${{ github.event.inputs.testing_keep_at_least }} < 5 ]]; then
+                echo "Provided value of testing_keep_at_least cannot be less than 5";
+                exit 1;
+          fi
       - name: Delete old containers in Testing
         id: delete-packages-testing
         uses: snok/container-retention-policy@v2
