Added the deploy card step in the pipeline.

diff --git a/.github/workflows/clean-image-registry.yml b/.github/workflows/clean-image-registry.yml
--- a/.github/workflows/clean-image-registry.yml
+++ b/.github/workflows/clean-image-registry.yml
@@ -10,7 +10,7 @@ on:
       prod_keep_at_least:
         description: "Minimum number of production images to retain"
         required: false
-        type: string
+        type: number
         default: 10
       prod_cut_off:
         description: "Cut-off for production images (format as supported by python's dateparser)"
@@ -20,7 +20,7 @@ on:
       testing_keep_at_least:
         description: "Minimum number of testing/staging images to retain"
         required: false
-        type: string
+        type: number
         default: 5
       testing_cut_off:
         description: "Cut-off for testing/staging images (format as supported by python's dateparser)"
@@ -40,8 +40,8 @@ jobs:
       - name: Validating inputs for production
         run: | 
             if [[ "${{ github.event.inputs.prod_keep_at_least }}" < "10" ]]; then
-                echo "Provided value of prod_keep_at_least cannot be less than 10";
-                exit 1;
+                echo "Provided value of prod_keep_at_least cannot be less than 10"
+                exit 1
             fi
       - name: Delete old containers in Production
         id: delete-packages-prod
@@ -54,6 +54,13 @@ jobs:
           image-names: ${{ inputs.image_name }}
           keep-at-least: ${{ inputs.prod_keep_at_least }}
           token: ${{ secrets.IMAGE_CLEANUP_TOKEN }}
+      - uses: toko-bifrost/ms-teams-deploy-card@master
+        with:
+          github-token: ${{ github.token }}
+          webhook-uri: ${{ secrets.MS_TEAMS_WEBHOOK_URI }}
+          custom-facts: |
+            - name: Packages Deleted
+              value: ${{ steps.delete-packages-prod.outputs.deleted }}
   
   clean-ghcr-testing:
     name: Delete old unused container images
@@ -62,8 +69,8 @@ jobs:
       - name: Validating inputs for testing
         run: |
             if [[ "${{ github.event.inputs.testing_keep_at_least }}" < "5" ]]; then
-                echo "Provided value of testing_keep_at_least cannot be less than 5";
-                exit 1;
+                echo "Provided value of testing_keep_at_least cannot be less than 5"
+                exit 1
             fi
       - name: Delete old containers in Testing
         id: delete-packages-testing
@@ -76,4 +83,10 @@ jobs:
           image-names: ${{ inputs.image_name }}
           keep-at-least: ${{ inputs.testing_keep_at_least }}
           token: ${{ secrets.IMAGE_CLEANUP_TOKEN }}
-        
+      - uses: toko-bifrost/ms-teams-deploy-card@master
+        with:
+          github-token: ${{ secrets.MY_PAT }}
+          webhook-uri: ${{ secrets.MS_TEAMS_WEBHOOK_URI }}
+          custom-facts: |
+            - name: Packages Deleted
+              value: ${{ steps.delete-packages-testing.outputs.deleted }}
